const familyTable = {
    page_1 : [
        {"title":"INTRODUCTION"},
        {"tag":"block", "pos":"begin", "color":"#FFA07A"}, /* LightSalmon */
        {"tag":"p", "step":"My interest in looking up my ancestors started when I was 15. My mom would occasionally talk about her relatives. I would get more information from my aunt and grandmother. I remember my mom saying that her Aunt Mary would tell her that we were related to the actress Rose Marie. Turns out she is my 6th cousin on my mother's side. I did write her about this, and she wrote me back, thankful but no interest."},
        {"tag":"p", "step":"With the information given, I was able to expand on what I heard at two places in Westerly, the Public Library and Saint Sebastian Cemetery. The card catalog at the library had a list of obituaries from the Westerly Sun. They also had microfiche of the Westerly Sun. With that, I was able to find more of my mom’s relatives that lived in the Westerly area as well as my dad’s relatives. This included finding Nana’s parent’s obituaries. I had no idea they lived in Bradford. In fact, my mom said they lived across the street from Nana. This would be the first reference that I would find on our dad’s side. I would also find the obituaries of our grandfather’s sister, Finita, who also lived in Bradford, and brother Michele who lived in Westerly. Once I started college, I put these records aside."},
        {"tag":"p", "step":"It wouldn’t be until 1998 that I would start looking again. I was living in Warwick, RI at the time and found the following places would help me in finding more records:"},
        {"tag":"ul open"},
        {"tag":"li", "step":"Family History Center (Mormon Church in Warwick) - Italian Records"},
        {"tag":"li", "step":"National Archives, Waltham, MA - US Census Records, Naturalization Records"},
        {"tag":"li", "step":"National Archives, Pittsfield, MA – Ship Passenger Lists (Immigration)"},
        {"tag":"li", "step":"RI State Archives, Providence, RI - 1925 and 1935 RI Census Records"},
        {"tag":"ul close"},
        {"tag":"p", "step":"Ancestry.com had started back in 1996 but wasn’t a big help at the time."},
        {"tag":"p", "step":"For the next 10 years, I would find more information on our dad’s side. I did ask Uncle Syl and Uncle Mandy and all I got was Uncle Syl saying that his dad never spoke about his family. I’m sure if I had asked my dad, he would have said the same."},
        {"tag":"p", "step":"I also searched genealogy posts online for people who might have some of the same ancestors as us. I found one, Barbara Bisignano Morrone, who had listed her great grandfather, Luigi Bisignano. Going through my records, he was our grandfather’s uncle. I also found out when a number of our Corina relatives came to the United States, he would be the one that would meet with them in New York. Through her, I was able to obtain more Bisignano records and I was able to give her Corina records. I also found Finita Corina's granddaughter, Barbara McClintock."},
        {"tag":"p", "step":"One of Finita’s daughter-in-law (possibly Kay) went to the same hairdresser as my mom. So, my mom asked her if she had any information on her mother-in-law and her family. A few weeks later, she gave my mom a picture. I looked at this picture and recognized our grandfather as well as his sister Finita and brother Michele. There were also two other women in the picture. From my Italian records, I figured one was Giorgetta and the other was Angiolina, our grandfather’s oldest sisters. I gave Uncle Rudy a copy of the picture the last time he came to Westerly and asked if he knew which sister was which. All he could remember was visiting one of them in New York but couldn’t remember which one."},
        {"tag":"p", "step":"I couldn’t find where these sisters lived until 2022. I was invited to David’s daughter’s, Lainey, graduation party. I made her a family album with a few pictures of the Corinas and Capalbos as well a partial family tree of each family. After that, I thought I would do another Google search of the two sisters and couldn’t believe that I finally found them. It turns out Angelina married Angelo Morrone and lived in Worcester, MA. Georgetta married Louis Fusaro and lived in Brooklyn. I’m guessing Uncle Rudy was thinking he visited his Aunt Georgetta."},
        {"tag":"p", "step":"The following pages will provide some of the information that I found on our Corina and Capalbo ancestors. Enjoy!"},
        {"tag":"p", "step":"Love from your cousin,<br>Kevin Corina<br>December 2023"},
        {"tag":"block", "pos":"end"}
    ],
    page_2 : [
        {"title":"ABOUT"},
        {"tag":"block", "pos":"begin", "color":"#5F9EA0"}, /* CadetBlue */
        {"tag":"h3", "step":"CORINA"},
        {"tag":"p", "step":"I have not found much about the origins of the Corina surname except for what is below and some information about Albanians coming to southern Italy in the late 15th century."},
        {"tag":"p", "step":"My grandfather, his brother Michele and sister Finita would live in Bradford, RI. His sister Georgetta would live in Brooklyn, NY and sister Angelina would live in Worcester, MA."},
        {"tag":"img", "file":"\\images\\about\\CorinaFamily.bmp", "alt":"Corina Family", "style":"display: block; width: 95%; margin: 5px auto; border-radius: 20px; box-shadow: 5px 5px 5px #000000"},
        {"tag":"block", "pos":"end"},
        {"tag":"block", "pos":"begin", "color":"#3CB371"}, /* MediumSeaGreen */
        {"tag":"h3", "step":"CAPALBO"},
        {"tag":"p", "step":"Many Capalbos lived in southern Rhode Island. My grandmother's family lived primarily in Bradford and her cousins were spread out between the towns of Westerly and Charlestown."},
        {"tag":"img", "file":"\\images\\about\\CapalboFamily.bmp", "alt":"Capalbo Family", "style":"display: block; width: 95%; margin: 5px auto; border-radius: 20px; box-shadow: 5px 5px 5px #000000"},
        {"tag":"img", "file":"\\images\\about\\Capalbo Coat of Arms.jpg", "alt":"Capalbo Coat of Arms", "style":"display: block; width: 200px; border: 3px outset #000000; margin: 10px auto"},
        {"tag":"block", "pos":"end"},
    ],
    page_4 : [
        {"title":"ITALY" },
        {"tag":"block", "pos":"begin", "color":"#5F9EA0"}, /* CadetBlue */
        {"tag":"h3", "step":"ACRI"},
        {"tag":"img", "file":"\\images\\italy\\acri.jpg", "alt":"Acri", "style":"display: block; width: 200px; margin: 5px auto;"},
        {"tag":"p", "step":"Three out of four of my grandparent’s ancestors lived in Acri including the Corinas, Capalbos and Toscanos. In fact, our grandfather Corina knew my grandmother Toscano, my mother’s mother."},
        {"tag":"p", "step":"The 1800s were not a good time for Acri and its neighboring towns. Between Napoleon’s troops, Bourbon rule and Italian unification, southern Italians would be poverty stricken. While northern Italians went through an Industrial Age, the southern Italians were mainly agricultural and had practically nothing to look forward to. "},
        {"tag":"p", "step":"This encouraged many southern Italians to go to the United States between the 1880s and 1920s."},
        {"tag":"p", "step":"Acri is about 40 km. (25 miles) north of the province capital of Cosenza. The map below depicts Calabria around 1890."},
        {"tag":"img", "file":"\\images\\italy\\MapCalabria1890.png", "alt":"Calabria Map", "style":"display: block;  width: 80%; margin: 5px auto; border-radius: 20px; box-shadow: 5px 5px 5px #000000"},
        {"tag":"block", "pos":"end"},
        {"tag":"block", "pos":"begin", "color":"#3CB371"}, /* MediumSeaGreen */
        {"tag":"h3", "step":"ITALIAN RECORDS"},
        {"tag":"p", "step":"During the late 18th century, Napoleon’s French Army would invade different parts of what is now Italy. In 1805, he formed the Kingdom of Italy and he declared himself King."},
        {"tag":"p", "step":"One of the things he did as King was change where vital records would be kept. Prior to 1809, the records were kept at the church that the person was attending. As these were Catholic Churches, most of these records would be written in Latin. Napoleon would change this by building town and city halls to keep these records and would be written in Italian."},
        {"tag":"p", "step":"Many years later, the Mormons were interested in finding genealogical records around the world and would add Family History Centers in many of their churches. I found out that there was a Family History Center in Warwick in the early 2000s. You don’t have to be Mormon to view records."},
        {"tag":"p", "step":"What I had to do was search for the town(s) in Italy where my ancestors lived. Luckily, the Corinas and Capalbos lived in Acri as well as the Toscanos (my other grandmother’s ancestors). I also searched for dates that they were born, married, or died. Once I determined what I wanted to view, the Family History Center would order the microfiche from the Salt Lake City library where the microfiche originated, and they would send a copy back to Warwick in about two weeks. Then I could go in the rooms with the microfiche machine to view the records. Once I found the record, I took it off the machine and went to the other room where someone could print the record that I found. If I reordered the microfiche two more time, they keep it at the local center. Otherwise, they sent it back to Salt Lake City."},
        {"tag":"p", "step":"Below is my grandfather Natale Corina’s birth record. I translated the important information on that record as an example."},
        {"tag":"img", "file":"\\images\\italy\\NataleCorinaBirth.JPG", "alt":"Italian Record example", "style":"display: block;  width: 80%; margin: 5px auto;"},
        {"tag":"block", "pos":"end"},
    ],
    page_5 : [
        {"title":"IMMIGRATION"},
        {"tag":"block", "pos":"begin", "color":"#5F9EA0"}, /* CadetBlue */
        {"tag":"h3", "step":"THE CORINAS GO TO AMERICA"},
        {"tag":"p", "step":"Let’s say one day you wake up and find out that the place you lived in has been unified with other places to form one nation. Then, you find out that the aristocrats and elite of the north are ruling you and your farmer and stone cutter friends in the south. Of course, you still must deal with the local rulers. What are you to do? You pack up your bag, kiss your mom, and tell her you’re off to America, the land of opportunity. Most likely you would go north to Naples to get on a ship and stay in steerage class for two weeks before arriving in New York Harbor."},
        {"tag":"p", "step":"They say between 1880 and 1924, over four million Italians came across and most of them were from Southern Italy. Many of them would end up on Ellis Island, though some ships went to other ports like Philadelphia, Providence, and Boston. With the ship came the Ship Passenger List with a list of all the people on the vessel. Most lists included the passenger’s name, age, where they came from, and who they were meeting with in the US, if anybody. Some would even include the town they lived in and their closest relative’s name from the country they left. "},
        {"tag":"p", "step":"Back in the early 2000s, the only places I would be able to find them nearby were in New York City or Pittsfield, MA. Pittsfield was a lot easier to get to and a nice drive through the Berkshire Mountains. So far, the oldest Ship Passenger List I found for a Corina relative was Luigi Bisignano, my great grandmother’s brother, in 1891. The ship must have gone to another part of New York City because Ellis Island didn’t open until the following year. The first of my direct Corina relatives to come over may have been my great grandfather, Salvatore Corina, in 1902. I’ll talk about this later. My grandfather’s sisters, Georgetta, and Angelina came in 1904 and Finita and Michele came in 1906. My grandfather Natale would come here in 1920."},
        {"tag":"p", "step":"My great grandfather, Francesco Giuseppe Capalbo, came in 1902 with his nephew, Pasquale Fiore. Francesco’s wife Annunziata Gradilone arrived in 1903 with her brother Angelo. Several of Francesco’s cousins from Acri would join him in the US."},
        {"tag":"block", "pos":"end"},
        {"tag":"block", "pos":"begin", "color":"#3CB371"}, /* MediumSeaGreen */
        {"tag":"h3", "step":"DID MY GREAT GRANDFATHER COME TO AMERICA?"},
        {"tag":"p", "step":"From time to time, I would find information that could not be fully proven. This was the case with my great grandfather, Salvatore Corina. "},
        {"tag":"p", "step":"Back in the early 2000s, I took a two and a half hour drive from Westerly to the National Archives in Pittsfield, MA. Back then, the National Archives in Waltham didn’t have Ship Passenger Lists and the alternative would have been to go to New York City. It was in Pittsfield where I would find when my grandfather and his siblings ended up on Ellis Island. However, I also found one that could be my ancestor."},
        {"tag":"p", "step":"The S.S. Marco Minghetti arrived in New York around May 31, 1902. In the Ship Passenger List on June 2nd was the name Salvatore Corina. According to the record, Salvatore was 45 from Acri and his destination was New York City. My great grandfather would have been 45 in December. Now who met with him at Ellis Island? I tried to enlarge the information below to get an idea who it was."},
        {"tag":"img", "file":"\\images\\immigration\\SalvatoreCorina.JPG", "alt":"Salvatore Corina immigration", "style":"display:block; width: 360px; margin: 5px auto; border-radius: 20px; box-shadow: 5px 5px 5px #000000"},    
        {"tag":"p", "step":"I see Luigi Bisignano who was Salvatore’s brother-in-law, but I also see “nobody” covering up some of Luigi’s name. If he did meet with Luigi, then maybe my great grandfather did come to the US, but what happened to him after he arrived and why did he come here? "},
        {"tag":"p", "step":"I have yet to find any US or State Census records with his name included. The only record I found was Salvatore’s son Michele’s Ship Passenger List in 1919. It lists Salvatore Corina as Michele’s nearest relative in the country that he left."},
        {"tag":"p", "step":"Did my great grandfather Corina come to the United States? All I can give you is a definite “maybe”."},
        {"tag":"block", "pos":"end"},
    ],
    page_6 : [
        {"title":"NATURALIZATION"},
        {"tag":"block", "pos":"begin", "color":"#5F9EA0"}, /* CadetBlue */
        {"tag":"h3", "step":"BECOMING US CITIZENS"},
        {"tag":"p", "step":"Once they landed here, many Italians wanted to become US citizens. To do that, they would have to be at least 18 years old and live in the US for at least 5 years. Then they would have to fill out a Naturalization form at a US District or Superior Court and meet with the judge who would ask you questions. Once the judge considers you a good candidate for citizenship, you’re in."},
        {"tag":"p", "step":"One thing that changed during this time was married women who came from another country. In September 1922, Congress passed a law saying that married women would no longer be considered US citizens because of their husband being a US citizen or naturalized. A perfect example of this was my mother’s parents. My grandfather became a US Citizen in 1918.  My grandmother came to America in 1920 and married my grandfather in November 1922. So, they thought that my grandmother would automatically be a US citizen. They wouldn’t realize that she wasn’t for 30 years. It wouldn’t be until the mid-1950s that my grandmother finally became a US citizen."},
        {"tag":"p", "step":"Naturalization records are like gold to a person doing their family history. They contain a lot of helpful information but were not always easy to find. Back when I was looking for information I went to the National Archives in Waltham, MA. I would go there searching Census records, but one of the people working there mentioned that had Naturalization records from courts in New England and New York. I would end up finding the records for my grandfather Natale Corina, his brother Michele and my great grandfather Francesco Giuseppe Capalbo among others."},
        {"tag":"p", "step":"To show what information is included in the Naturalization form, I will use my grandfather Natale’s form as an example."},
        {"tag":"p", "step":"First, they show where he currently resides and his current occupation."},
        {"tag":"img", "file":"\\images\\naturalization\\naturalization1.JPG", "alt":"Naturalization record", "style":"display:block; width: 90%; margin: 5px auto;"},
        {"tag":"p", "step":"Next, they have his immigration information including where and when he left, where and when he arrived, and the name of the ship he was on."},
        {"tag":"img", "file":"\\images\\naturalization\\naturalization2.JPG", "alt":"Naturalization record", "style":"display:block; width: 90%; margin: 5px auto;"},
        {"tag":"p", "step":"Then it shows where he declared his intention to become a US citizen."},
        {"tag":"img", "file":"\\images\\naturalization\\naturalization3.JPG", "alt":"Naturalization record", "style":"display:block; width: 90%; margin: 5px auto;"},
        {"tag":"p", "step":"Next comes the family information. Here we have his wife’s name, date of birth, place of birth, and where she currently resides. Of course, dates are not always correct. As we know, Nana was born in November, not October. They would also include any children with their date of birth and where they were born and reside."},
        {"tag":"img", "file":"\\images\\naturalization\\naturalization4.JPG", "alt":"Naturalization record", "style":"display:block; width: 90%; margin: 5px auto;"},
        {"tag":"p", "step":"Then he would renounce the king of the country that he came from and prove that he could speak English."},
        {"tag":"p", "step":"After that comes something that you would not get on any other forms mentioned in this book, his signatures. In the instance that the person declaring citizenship cannot write his name, the clerk filling out the form would put his name and the person would put an “X” above the name."},
        {"tag":"img", "file":"\\images\\naturalization\\naturalization5.JPG", "alt":"Naturalization record", "style":"display:block; width: 90%; margin: 5px auto;"},
        {"tag":"p", "step":"He would also need two witnesses who are US Citizens and have known him for at least 5 years to verify that he is qualified to become a citizen."},
        {"tag":"img", "file":"\\images\\naturalization\\naturalization6.JPG", "alt":"Naturalization record", "style":"display:block; width: 90%; margin: 5px auto;"},
        {"tag":"p", "step":"Not included here were features of the person like height, weight, hair and eye color and distinguishing marks. Then the form is signed by the clerk and the judge and at the bottom is the certificate number and date of Naturalization. Some of the Naturalization records had photos of the applicant. Unfortunately, I did find any of those."},   
        {"tag":"block", "pos":"end"},
    ],
    page_7 : [
        {"title":"LIVING IN AMERICA"},
        {"tag":"block", "pos":"begin", "color":"#5F9EA0"}, /* CadetBlue */
        {"tag":"p", "step":"After Luigi Bisignano arrived in the United States in the 1890s, he would probably live in a tenement building in what would become known as the “Little Italy” section of southern Manhattan Island. When Georgetta and Angelina Corina arrived in 1904, Luigi was living at 5 Mulberry Street. Then he would live at 12 Roosevelt Street into the 1920s. His sister Cristina lived across the street at 13 Roosevelt Street. Finally, he moved to 990 Coney Island Avenue in Brooklyn before 1930."},
        {"tag":"p", "step":"Georgetta would marry Luigi Fusaro in 1905. They would live at 9 James Street. According to brother Michele’s return to the US in 1919, he was met by brother-in-law Luigi who was living at 472 Pearl Street. Sometime before 1930, they moved to 1067 Coney Island Avenue in Brooklyn where Georgette would live until she passed away in 1940. Luigi worked as a porter at Guaranty Bank Company while Georgette would have her own small business in Brooklyn."},
        {"tag":"p", "step":"Angelina would marry Angelo Morrone in 1906. Shortly after, they must have moved to Worcester, MA as their oldest son, Frank, was born there in 1907. They lived at 13 Norfolk Street and later at Fenwood Road. Angelo worked at a Tannery up till the 1940s. Angelina was found in the 1940 US Census but not in the 1950. I’m guessing she passed away sometime in the 1940s."},
        {"tag":"img", "file":"\\images\\america\\Corina New York City Locations.JPG", "alt":"Corina's in New York City", "style":"display:block; width: 90%; margin: 5px auto;"},
        {"tag":"img", "file":"\\images\\america\\Lower East Side 1847.jpg", "alt":"New York City Lower East Side", "style":"display:block; width: 60%; margin: 5px auto;"},
        {"tag":"img", "file":"\\images\\america\\RooseveltSt.jpg", "alt":"Roosevelt Street New York City", "style":"display:block; width: 60%; margin: 5px auto;"},
        {"tag":"img", "file":"\\images\\america\\RooseveltStText.jpg", "alt":"Roosevelt Street New York City", "style":"display:block; width: 60%; margin: 5px auto;"},
        {"tag":"p", "step":"Finita and Michele would arrive at Ellis Island in 1906 and met by Uncle Luigi."},
        {"tag":"p", "step":"Finita would marry Annunziato Vuono in 1908. When Annunziato first filled out the form of intention to become a US citizen in 1912, he was living at 472 Pearl Street, New York, NY. I found out by Finita's granddaughter, Barbara McClintock, that her mother Florence had meningitis when she was a baby. The doctor told her parents to take her to the country for her health. Barbara thinks they moved to Bradford around 1915 or 1916, but according to Annunziato's Naturalization record, he was living at 13 Oak Street in New York. The 1920 US census showed him living at North Main Street in Bradford. Finita would live in Bradford until she passed away in 1960."},
        {"tag":"p", "step":"I always thought our Corina relatives moved here to be stone cutters like other Italians that came to Westerly and Bradford. Who knew it was because of a poor sick child. Good news! Florence recovered and would live to the age of 74."},
        {"tag":"p", "step":"Michele stayed in the US until 1915. According to a Ship Passenger List in 1919, he returned and was met by his brother-in-law, Luigi Fusaro, but I don’t think he stayed in New York too long as he would move to Bradford, RI. I haven’t found any other records for him except for his obituary in 1955. According to the obituary, he fought in the Italian army during World War I and was wounded in the front lines. I remember my mom told me he had a metal plate on his head. He did landscaping in Westerly and Watch Hill. According to the police, he fell against the curb and fractured his skull. He never married. "},
        {"tag":"p", "step":"Our grandfather, Natale, came in 1920 and would meet up with his brother, Michele, in Bradford. He would marry our grandmother in 1923 and have two sons, Sylvester and Frank before moving to Brooklyn. Julio would be born in Brooklyn in 1928. So sometime between 1926 and 1928, they moved to Brooklyn. They were still there in 1930 on 954 Coney Island Avenue, but before Rudy was born in 1931, they were back in Bradford. He would go back to New York and Italy. I found a ship passenger list of his from 1948. Shortly after that, he would leave Bradford and live in Wantagh, Long Island. His wife and children stayed in Bradford, RI. He would run his shoe repair shop in Wantagh until he passed away in 1955."},
        {"tag":"p", "step":"There was one sister who never came to America, Margaret (Immaculata). She was born two years after our grandfather in 1897. My grandmother on my mother’s side went to Acri in 1968 to see her siblings for the first time in 48 years. She told me she saw Margaret there. So, as of 1968, she was the only one of our grandfather’s siblings still living. "},
        {"tag":"p", "step":"By the 1950s, these tenement buildings would be razed:"},
        {"tag":"ul open"},
        {"tag":"li", "step":"472 Pearl Street is now the Southern District of New York Court Building,"},
        {"tag":"li", "step":"5 Mulberry Street is now part of Columbus Park."},
        {"tag":"li", "step":"Oak Street, Roosevelt Street and some of the streets around them no longer exist."},
        {"tag":"li", "step":"James Street still exists, but 9 James Street no longer exists. I'm guessing St. James Place expanded where this building once stood."},
        {"tag":"ul close"},
        {"tag":"img", "file":"\\images\\america\\LowerEastSideToday.JPG", "alt":"Lower East Side Today", "style":"display:block; width: 90%; margin: 5px auto;"},
        {"tag":"p", "step":"The section of Coney Island Avenue in Brooklyn where our relatives lived is now known as 'Little Pakistan' as people from Pakistan have moved there since the 1980s."},
        {"tag":"block", "pos":"end"}, 
        {"title":"SOME LOCATIONS WHERE CORINA RELATIVES WOULD LIVE"},
        {"tag":"img", "file":"\\images\\america\\Corina Northeast Map.JPG", "alt":"Corina Northeast Map", "style":"display:block; width: 90%; margin: 5px auto;"},
    ],
}


