const family = [
    {"id": 1,
     "fname": "Julio", 
     "lname": "Corina", 
     "birth": "03/21/1928", 
     "birthplace": "Brooklyn, NY",
     "death": "05/04/1980", 
     "deathplace": "Westerly, RI",
     "father": 2, 
     "mother": 3},
     {"id": 2,
     "fname": "Natale", 
     "lname": "Corina", 
     "birth": "01/12/1895",
     "birthplace": "Acri, Italy", 
     "death": "10/01/1955", 
     "deathplace": "Wantagh, NY",
     "father": 4, 
     "mother": 5},
     {"id": 3,
     "fname": "Antonnette", 
     "lname": "Capalbo", 
     "birth": "11/04/1907",
     "birthplace": "Bradford, RI", 
     "death": "08/19/1981",
     "deathplace": "Bradford, RI",
     "father": 6, 
     "mother": 7},
]



